"""Add has_consent to members

Revision ID: 61aff97fdd77
Revises: 9499858ceef5
Create Date: 2026-03-06 15:34:14.664087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "61aff97fdd77"
down_revision: Union[str, Sequence[str], None] = "9499858ceef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_members", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "has_consent", sa.Boolean(), nullable=False, server_default=sa.text("0")
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_members", schema=None) as batch_op:
        batch_op.drop_column("has_consent")

    # ### end Alembic commands ###
