"""add_checkout_support

Revision ID: 9499858ceef5
Revises: 2c0e0f2c3bf3
Create Date: 2026-03-06 06:20:16.586445

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9499858ceef5"
down_revision: Union[str, Sequence[str], None] = "2c0e0f2c3bf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_groups", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "track_checkout",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("0"),
            )
        )

    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("check_out_time", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_sessions", schema=None) as batch_op:
        batch_op.drop_column("check_out_time")

    with op.batch_alter_table("attendance_groups", schema=None) as batch_op:
        batch_op.drop_column("track_checkout")

    # ### end Alembic commands ###
