"""Add liveness detection setting

Revision ID: fdabcb4e0dab
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 00:30:10.932222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fdabcb4e0dab"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "enable_liveness_detection",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("1"),
            )
        )

    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_org_id"))
        batch_op.drop_index(batch_op.f("ix_audit_target_id"))
        batch_op.create_index(
            batch_op.f("ix_audit_logs_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_organization_id"),
            ["organization_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_logs_timestamp"), ["timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_timestamp"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_target_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_organization_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))
        batch_op.create_index(
            batch_op.f("ix_audit_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_org_id"), ["organization_id"], unique=False
        )

    with op.batch_alter_table("attendance_settings", schema=None) as batch_op:
        batch_op.drop_column("enable_liveness_detection")

    # ### end Alembic commands ###
